### ISSUE TITLE
Get current version from latest tag

### ISSUE THREAD

**Issue by rising3** [rising3/semver-gradle-plugin#3]
Add new feature for Get current version from latest tag.

### Summary

**FILE MODE:**
1. Get current version from file. (gradle.properties, package.json, etc.)
2. Update to new version, save to files.
3. Create a git commit of save files.
4. Create a git tag of new version.

**TAG MODE:**
1. Get latest tag for git.
2. Analyze tag, convert to semantic version.(current version)
3. Update to new version, save to file.
4. Create a git tag of new version.
5. Push tag to remote.

GIT CONTROL | FILE MODE(DEFAULT) | TAG MODE(DEFAULT)
-- | -- | --
CREATE(UPDATE) VERSION FILES |  Y | Y
CREATE VERSION COMMIT | Y | N
CREATE VERSION TAG | Y | Y
PUSH COMMIT | N | N
PUSH TAG | N | Y

### Plugin Extension
The following add/change properties:
Property Name | Type | Default value | Description
-- | -- | -- | --
[NEW] <BR> manageVersion | String | 'file' | Choice 'FILE' or 'TAG' .
[CHANGE] <BR> filename | String | 'gradle.properties' | Change the filename of&nbsp;version&nbsp;property. <BR> (FILE MODE Only)
[CHANGE] <BR> noGitCommand | boolean | false | Even enable or disable the git command behavior entirely. <BR> (FILE MODE Only)
[CHANGE] <BR> noGitInit | boolean | true | Even enable or disable the git init behavior entirely. <BR> (FILE MODE Only)
[NEW] <BR>  noGitCommitVersion | boolean | false | Even enable or disable the git commit behavior entirely. <BR> (FILE MODE Only)
[CHANGE] <BR> noGitTagVersion | boolean | false | Even enable or disable the git tagging behavior entirely. <BR> (FILE MODE Only)
[NEW] <BR> noGitPush | boolean | true | Even enable or disable the git push  behavior entirely. <BR> (FILE MODE Only)
[NEW] <BR> noGitPushTag | boolean | true | Even enable or disable the git push tag behavior entirely. <BR> (FILE MODE Only)

**Comment by nloboda** [comment]
Getting version from tag makes perfect sense. 

However it might be tricky to make it work with several branches. 
For example:
you've version 1.x and 2.x and branches 
release_1 (you tag from this branch say, v1.0.1, v.1.0.2, v.1.1.9 )
release_2 (you tag from this branch, say v2.0.4, v.2.0.6, v.2.6.2 )

say latest version was v.2.6.2, then if you try to release next version from 1.x branch it will be bumped to 2.6.3. 

Different solution might be getting latest tag from branch you're currently. in this case bump from   v.1.1.9 will be  v.1.1.10
and from v.2.6.2 will be v.2.6.3 which allow users to maintain several active versions. 

Would be really nice to chat with you over this issue, and I think I could send you merge request this Sunday or something.

**Comment by rising3** [comment]
@nloboda 

It's a good point.I'm aware of the point.
When releasing on a maintenance branch, we plan to guess the branch name and get the next version from the branch name.

TAG LISTS

* v2.1.0(latest) 
* v2.0.0
* v1.1.0 -> 1.x
* v1.0.2
* v1.0.1
* v1.0.0 -> 1.0.x

e.g.) when releasing on 1.0.x branch

* current: v1.0.2
* next: v1.0.3

However, if you are releasing on the maintenance branch, you must meet the following requirements:

* maintenance branch name.
  * MAJOR.MINOR.X
  * MAJOR.X
* The valid version number range is the specified minor or revision number range.
  * e.g) 1.0.x branch
    1.0.2 Valid
    1.1.2 Invalid
    3.0.0 Invalid
  * e.g) 1.x branch
    1.2.0 Valid
    1.3.0 Valid
    2.0.0 Invalid
    3.0.0 Invalid

thx.

**Comment by nloboda** [comment]
Thanks. I'll try to come up with something tomorrow

**Comment by nloboda** [comment]
Hi @rising3 , 

I've did some work on storing versions in tags. 
https://github.com/nloboda/semver-gradle-plugin/pull/1/files

This is JFYI update, I don't feel like it's ready to be merged yet. 
I'll try to adjust this to adhere ticket specification and coding standard tomorrow. and drop-in update. 

Thanks!

**Comment by nloboda** [comment]
@rising3 

Hi, I kindly request for comments on pr. 
https://github.com/rising3/semver-gradle-plugin/pull/5

Regards, Nikolay.
